version: 2
updates:
    -
        package-ecosystem: composer
        directory: "/"
        schedule:
            interval: monthly
        versioning-strategy: lockfile-only
        groups:
            ci-tools:
                patterns:
                    - "phpstan/*"
                    - "shipmonk/*"
                    - "phpunit/*"
                    - "editorconfig-checker/*"
                    - "ergebnis/composer-normalize"
                    - "slevomat/coding-standard"
                update-types:
                    - patch
                    - minor
